# Generated by Django 3.2.25 on 2024-11-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('Fuel_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Fuel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gas_Stations',
            fields=[
                ('id_stations', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('price_history_id', models.BigAutoField(db_column='Price_History_Id', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='Price')),
                ('change_date', models.DateTimeField(db_column='Change_Date')),
            ],
            options={
                'db_table': 'Price_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationFuel',
            fields=[
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Update_Date', models.DateTimeField(auto_now=True)),
                ('Station_Fuel_Id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Station_Fuel',
                'managed': False,
            },
        ),
    ]
