# Generated by Django 3.2.25 on 2024-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.BigAutoField(db_column='Fuel_Id', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Fuel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gas_Stations',
            fields=[
                ('Station_Id', models.BigAutoField(db_column='Station_Id', primary_key=True, serialize=False)),
                ('Address', models.CharField(db_column='Address', max_length=100)),
                ('City', models.CharField(db_column='City', max_length=100)),
                ('Zip', models.CharField(db_column='Postal_Code', max_length=100)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
                ('Latitude', models.FloatField(db_column='Latitude')),
                ('Longitude', models.FloatField(db_column='Longitude')),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price_history',
            fields=[
                ('Price_Id', models.BigAutoField(db_column='Price_History_Id', primary_key=True, serialize=False)),
                ('Price', models.FloatField(db_column='Price')),
                ('Date', models.DateTimeField(db_column='Change_Date')),
            ],
            options={
                'db_table': 'Price_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station_Fuel',
            fields=[
                ('Station_Fuel_Id', models.BigAutoField(db_column='Station_Fuel_Id', primary_key=True, serialize=False)),
                ('Price', models.FloatField(db_column='Price')),
                ('Date', models.DateTimeField(db_column='Update_Date')),
            ],
            options={
                'db_table': 'Station_Fuel',
                'managed': False,
            },
        ),
    ]
