# Generated by Django 3.2.25 on 2024-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('price_history_id', models.BigAutoField(db_column='Price_History_Id', primary_key=True, serialize=False)),
                ('price', models.FloatField(db_column='Price')),
                ('change_date', models.DateTimeField(db_column='Change_Date')),
            ],
            options={
                'db_table': 'Price_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Station_Fuel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Price_history',
        ),
        migrations.DeleteModel(
            name='Station_Fuel',
        ),
    ]
