# Generated by Django 3.2.25 on 2024-11-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_prices', '0002_auto_20241114_2106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuel',
            table='Fuels',
        ),
    ]
