# Generated by Django 3.2.25 on 2024-11-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_prices', '0002_alter_gas_stations_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gas_stations',
            table='Gas_Stations',
        ),
    ]
