# Generated by Django 3.2.25 on 2024-11-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_prices', '0003_alter_fuel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuel',
            table='Fuel',
        ),
    ]
