# Generated by Django 3.2.25 on 2024-12-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Stations',
            fields=[
                ('id_stations', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRating',
            fields=[
                ('id_stations', models.OneToOneField(db_column='id_stations', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='station_details.gas_stations')),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_rating',
                'managed': False,
            },
        ),
    ]
