# Generated by Django 3.2.25 on 2024-12-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas_stations',
            options={},
        ),
    ]
