# Generated by Django 5.1.2 on 2024-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.BigAutoField(db_column='Fuel_Id', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Fuel',
                'managed': False,
            },
        ),
    ]
