# Generated by Django 5.1.2 on 2024-11-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuel',
            table='Fuel',
        ),
    ]
