# Generated by Django 5.1.3 on 2024-11-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Stations',
            fields=[
                ('Station_Id', models.BigAutoField(db_column='Station_Id', primary_key=True, serialize=False)),
                ('Address', models.CharField(db_column='Address', max_length=100)),
                ('City', models.CharField(db_column='City', max_length=100)),
                ('Zip', models.CharField(db_column='Postal_Code', max_length=100)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
                ('Latitude', models.FloatField(db_column='Latitude')),
                ('Longitude', models.FloatField(db_column='Longitude')),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('Notification_Id', models.BigAutoField(db_column='Notification_Id', primary_key=True, serialize=False)),
                ('Price_Threshold', models.FloatField(db_column='Price_Threshold')),
                ('Status', models.CharField(db_column='Status', max_length=100)),
                ('Setting_Date', models.DateTimeField(db_column='Setting_Date')),
            ],
            options={
                'db_table': 'Notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price_history',
            fields=[
                ('Price_Id', models.BigAutoField(db_column='Price_History_Id', primary_key=True, serialize=False)),
                ('Price', models.FloatField(db_column='Price')),
                ('Date', models.DateTimeField(db_column='Change_Date')),
            ],
            options={
                'db_table': 'Price_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('Promotion_Id', models.BigAutoField(db_column='Promotions_Id', primary_key=True, serialize=False)),
                ('Start_Date', models.DateTimeField(db_column='Start_Date')),
                ('End_Date', models.DateTimeField(db_column='End_Date')),
                ('Comment', models.CharField(db_column='Promotion_Description', max_length=100)),
            ],
            options={
                'db_table': 'Promotions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_Id', models.BigAutoField(db_column='Reports_Id', primary_key=True, serialize=False)),
                ('Reported_price', models.FloatField(db_column='Reported_Price')),
                ('Reported_date', models.DateTimeField(db_column='Report_Date')),
                ('Comment', models.CharField(db_column='Comment', max_length=100)),
            ],
            options={
                'db_table': 'Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Role_Id', models.BigAutoField(db_column='Role_Id', primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(db_column='Role_Name', max_length=100)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station_Fuel',
            fields=[
                ('Station_Fuel_Id', models.BigAutoField(db_column='Station_Fuel_Id', primary_key=True, serialize=False)),
                ('Price', models.FloatField(db_column='Price')),
                ('Date', models.DateTimeField(db_column='Update_Date')),
            ],
            options={
                'db_table': 'Station_Fuel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station_Rev',
            fields=[
                ('Station_Reviews_Id', models.BigAutoField(db_column='Station_Reviews_Id', primary_key=True, serialize=False)),
                ('Rating', models.FloatField(db_column='Rating')),
                ('Comment', models.CharField(db_column='Comment', max_length=100)),
                ('Date', models.DateTimeField(db_column='Review_Date')),
            ],
            options={
                'db_table': 'Station_Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('Last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('Is_super_user', models.BooleanField(db_column='is_superuser')),
                ('Username', models.CharField(db_column='username', max_length=100)),
                ('First_name', models.CharField(db_column='first_name', max_length=100)),
                ('Last_name', models.CharField(db_column='last_name', max_length=100)),
                ('Email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('Is_staff', models.BooleanField(db_column='is_staff')),
                ('Is_active', models.BooleanField(db_column='is_active')),
                ('Date_joined', models.DateTimeField(db_column='date_joined')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite_Station',
            fields=[
                ('Favorite_Id', models.BigAutoField(db_column='Favorite_Stations_Id', primary_key=True, serialize=False)),
                ('Station_Id', models.ForeignKey(db_column='Station_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.gas_stations')),
                ('User_Id', models.ForeignKey(db_column='User_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.users')),
            ],
            options={
                'db_table': 'Favorite_Stations',
                'managed': True,
            },
        ),
    ]
