# Generated by Django 3.2.25 on 2024-12-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_favorite_station_gas_stations_notifications_price_history_promotion_report_roles_station_fuel_statio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRating',
            fields=[
                ('id_stations', models.OneToOneField(db_column='id_stations', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='stations.gas_stations')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_rating',
                'managed': False,
            },
        ),
    ]
