# Generated by Django 5.1.3 on 2024-11-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_gas_stations_notifications_price_history_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_station',
            name='User_Id',
            field=models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.users'),
        ),
    ]
