# Generated by Django 3.2.25 on 2024-12-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_warning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warning',
            options={'managed': False},
        ),
    ]
