# Generated by Django 5.1.3 on 2024-12-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='complain',
        ),
    ]
