# Generated by Django 3.2.25 on 2024-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_warning_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rating_record',
                'managed': False,
            },
        ),
    ]
