# Generated by Django 5.1.3 on 2024-12-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_report_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
