# Generated by Django 5.1.3 on 2024-11-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_favorite_station_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_station',
            name='Station_Id',
            field=models.ForeignKey(db_column='id_stations', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.gas_stations'),
        ),
        migrations.AlterModelTable(
            name='gas_stations',
            table='stations',
        ),
    ]
