# Generated by Django 5.1.3 on 2024-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_Id', models.BigAutoField(db_column='Reports_Id', primary_key=True, serialize=False)),
                ('Reported_price', models.FloatField(db_column='Reported_Price')),
                ('Reported_date', models.DateTimeField(db_column='Report_Date')),
                ('Comment', models.CharField(db_column='Comment', max_length=100)),
            ],
            options={
                'db_table': 'Reports',
                'managed': False,
            },
        ),
    ]
