# Generated by Django 3.2.25 on 2024-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Stations',
            fields=[
                ('Station_Id', models.BigAutoField(db_column='id_stations', primary_key=True, serialize=False)),
                ('Address', models.CharField(db_column='address', max_length=100)),
                ('City', models.CharField(db_column='city', max_length=100)),
                ('Zip', models.CharField(db_column='postal_code', max_length=100)),
                ('Name', models.CharField(db_column='name', max_length=100)),
                ('Latitude', models.FloatField(db_column='latitude')),
                ('Longitude', models.FloatField(db_column='longitude')),
                ('Phone', models.CharField(db_column='phone', max_length=100)),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GasStation',
        ),
    ]
