# Generated by Django 3.2.25 on 2024-11-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id_stations', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Gas_Stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('zip_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'postal_code',
                'managed': False,
            },
        ),
    ]
