# Generated by Django 5.1.3 on 2024-11-11 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_sample_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', 'Postal code must be in the format XX-XXX')]),
        ),
    ]
