# Generated by Django 5.1.3 on 2024-11-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fuel_type',
            field=models.CharField(default='Gaz', max_length=50),
        ),
    ]
